# Generated by Django 5.1.3 on 2024-11-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_profile_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
    ]
